acejump/AceJump

src/com/johnlindquist/acejump/keycommands/DefaultKeyCommand.kt

I've found out that jumping didn't work when using target mode. Additionally when using normal mode, when having multiple matches, hitting a key which was not on the list, would lead to a behaviour as described in an issue #25.
I believe the reason was that the characters were collected, even if they could never lead to a successful jump, and pressing more characters would just increase the buffer of collected chars (the target jump didn't work because ';' was also collected). I think this commit would fix it.
PS. the project didn't compile and I had to change some stuff, but that's not included in the pull-request, as today was literally first time I did something with Kotlin, and I'm not sure if that's general problem or my misconfiguration.

Fix #25 and jumping when using target mode

---

build.gradle.kts
src/main/kotlin/com/johnlindquist/acejump/control/Handler.kt

Since AceJump is derived from "ace-jump-mode" of Emacs,
I think that many users make Keymap as Emacs.
It is an already closed issue (#211)
Please adopt it if you like.

add escActionHandler for #211 (Ctrl-G in Emacs mode)

---

src/main/kotlin/org/acejump/control/Handler.kt

This PR solves https://github.com/acejump/AceJump/issues/278.
Before jump AceJump saves caret shape that is stored in the settings. Since IdeaVim plugin
changes the caret shape at runtime, it recovers incorrectly if the user uses a normal caret and the current caret shape is block.
My suggestion is to take the shape from the current state of the caret.

IdeaVim: Save caret shape after jump

---

src/main/kotlin/org/acejump/control/Handler.kt
src/main/kotlin/org/acejump/control/Scroller.kt

Don't restore scroll and caret on disposed editor

---

src/main/kotlin/org/acejump/view/Marker.kt

After the performing regex search, small green flashes appear in the editor. Looks like IJ tries to paint the marks with the length of the regex pattern, but it should not happen in regex mode.
With this pull request, I suggest to explicitly set searchWidth to 0 in case of regex search.

Remove green flashes after performing regex search

---

src/main/kotlin/org/acejump/control/Handler.kt
src/main/kotlin/org/acejump/search/AceUtil.kt
src/main/kotlin/org/acejump/search/Finder.kt
src/main/kotlin/org/acejump/view/Boundary.kt

With the power of AceJump it is possible to implement 80 of 87 easymotion commands. This is a wonderful result, I personally expected much fewer commands supported! The rest 7 commands don't seem to be a big deal as well but require a few extra days and more complicated changes in AceJump (some of the commands support jumps between editors). Anyway, we don't have any plans to implement the rest commands in the nearest future.
The result of the work is presented as a [IdeaVim-EasyMotion](https://github.com/AlexPl292/IdeaVim-EasyMotion) plugin. In order to make all the things work, we have to request some changes in the AceJump plugin. The given pull request consists out of 5 commits that provide some simple extensions of AceJump functionality. Below I'll describe the ideas behinds the …

IdeaVim integration

---

build.gradle.kts

I suppose that [this](https://github.com/JetBrains/gradle-intellij-plugin/issues/377) question was regarding the name of the resulting plugin archive.
With the existing script, the naming rule will apply to the *all* zip tasks, which is incorrect. This fact causes the problem that AceJump currently has a bit "incorrect" structure and even IJ plugin marketplace resolved it fine, it's a bit tricky to make a dependency to AceJump. `intellij` section in gradle script just cannot resolve such structure and it's needed to add the dependency manually.
This pull request reduces the naming rule only to the result of the `buildPlugin` task.
Additionally, here is a pic of the existing plugin structure:
And here is a fixed structure:

Apply the name of the archive only to the result of buildPlugin task

---

src/main/kotlin/org/acejump/config/AceConfig.kt
src/main/kotlin/org/acejump/label/Pattern.kt
src/main/kotlin/org/acejump/label/Solver.kt
src/main/kotlin/org/acejump/label/Tagger.kt

Hey @breandan,
looks like there is a circular dependency between AceConfig and Pattern initialization.
[Here](https://github.com/acejump/AceJump/blob/master/src/main/kotlin/org/acejump/label/Pattern.kt#L24) `AceConfig` is needed for `Pattern` and [here](https://github.com/acejump/AceJump/blob/master/src/main/kotlin/org/acejump/config/AceConfig.kt#L38) `Pattern` is required for `AceConfig`.
If you don't see any good fix for this, here is my quickfix solution that can be used for the release before the proper one. 👍

Quickfix for for circular dependency between AceConfig and Pattern

---

src/main/kotlin/org/acejump/control/Listener.kt
src/main/kotlin/org/acejump/control/Selector.kt
src/main/kotlin/org/acejump/control/Trigger.kt
src/main/kotlin/org/acejump/label/Pattern.kt
src/main/kotlin/org/acejump/label/Solver.kt
src/main/kotlin/org/acejump/search/AceUtil.kt
src/main/kotlin/org/acejump/search/Finder.kt
src/main/kotlin/org/acejump/view/Marker.kt

Was trying the plugin out and immediately ran into severe performance issues, so I figured I'd give some optimizations a shot.
Here are my results with the `test tag latency` test:
```
Before: 25.1s (avg 185ms)
After:   9.2s (avg  28ms)
```
I verified that unit tests succeed (apart from `test pinyin selection` which had a compile error in `master`, not sure if you know), and that the order of tags has not changed and basic uses of the plugin still work, but since I've only used it for a few minutes so far it's possible something subtle may have changed that I didn't catch.
In a few places I avoided recomputing things that don't change, those cases should be obvious.
In `Solver.tryToAssignTag`, the first major change was storing used indices in an `IntSet` which already brought it down …

Fixed several performance issues and stuttering

---

src/main/kotlin/org/acejump/search/Finder.kt
src/main/kotlin/org/acejump/view/Marker.kt

It's not trivial to test how much faster this is, so I recorded a [video](https://github.com/acejump/AceJump/files/5575070/rendering.zip) and counted frames between the loudest point of the key press waveform and the when search highlights (not markers) started appearing on the screen. Excluding the first key press because it takes a bit longer, the averages are:
```
Before: 0.424s
After:  0.050s
```
One thing I did was
```java
// TODO this is a lag-fest, results should be cached before this gets turned back on
//if (highlighter.startOffset == Selector.nearestVisibleMatches().firstOrNull()) {
//  color = naturalCaretColor
//  drawLine(start.x, startY, start.x, startY + rectHeight)
//}
```
As far as I can tell this only adds a small caret highlight, but repeatedly calling …

Optimize rendering by bulk-adding text highlights and reducing unnecessary work

---

src/main/kotlin/org/acejump/config/AceConfig.kt
src/main/kotlin/org/acejump/config/AceConfigurable.kt
src/main/kotlin/org/acejump/config/AceSettings.kt
src/main/kotlin/org/acejump/config/AceSettingsPanel.kt
src/main/kotlin/org/acejump/view/Model.kt
src/main/resources/AceResources.properties

On my particular configuration, the rounded corners often go underneath letters which makes them unnecessarily difficult to read, so I added an option to turn the rounding off.

Add option to switch between straight and rounded tag corners

---

src/main/kotlin/org/acejump/config/AceConfig.kt
src/main/kotlin/org/acejump/config/AceConfigurable.kt
src/main/kotlin/org/acejump/config/AceSettings.kt
src/main/kotlin/org/acejump/config/AceSettingsPanel.kt
src/main/kotlin/org/acejump/search/Finder.kt
src/main/kotlin/org/acejump/search/Scanner.kt
src/main/kotlin/org/acejump/view/Model.kt
src/main/resources/AceResources.properties

Should resolve #217 by adding option to only search in visible area. As I mentioned in the issue, the boundary checks only consider lines, so it's still possible to improve this for files with very long lines but this is good for the vast majority of cases.
The second commit also increases the limit for what's considered a large file from 30k to 100k, and changes the decision, whether search should be parallelized, to consider the total boundary size instead of hard-coding it to full file (could be useful, for ex. if a file had *extremely* long lines where screen boundary is also huge, or if more boundaries where implemented such as one that searches from caret to end of a large file).

Add option to only consider visible area and increase limit for what is considered a large file

---

src/main/kotlin/org/acejump/session/Session.kt
src/test/kotlin/ExternalUsageTest.kt

Another PR!
regex search allows you to define custom boundaries, but a regular jump not. Here is a change that adds a version of `toggleJumpMode` with `boundaries` parameter.

Allow defining jump mode with boundaries

---

CHANGES.md
build.gradle.kts
src/main/kotlin/org/acejump/AceUtil.kt
src/main/kotlin/org/acejump/action/AceAction.kt
src/main/kotlin/org/acejump/action/TagJumper.kt
src/main/kotlin/org/acejump/action/TagVisitor.kt
src/main/kotlin/org/acejump/search/SearchProcessor.kt
src/main/kotlin/org/acejump/search/Solver.kt
src/main/kotlin/org/acejump/search/Tag.kt
src/main/kotlin/org/acejump/search/Tagger.kt
src/main/kotlin/org/acejump/search/TaggingResult.kt
src/main/kotlin/org/acejump/session/Session.kt
src/main/kotlin/org/acejump/session/SessionManager.kt
src/main/kotlin/org/acejump/view/TagCanvas.kt
src/main/kotlin/org/acejump/view/TagFont.kt
src/main/kotlin/org/acejump/view/TagMarker.kt
src/main/kotlin/org/acejump/view/TextHighlighter.kt
src/test/kotlin/ExternalUsageTest.kt
src/test/kotlin/org/acejump/test/util/BaseTest.kt

#370
> Do you plan to disable auto-scrolling in split-screen sessions or do you think it makes sense to scroll multiple editors to the nearest available match?
For now I made it so only the main editor scrolls if none of the editors have any visible matches. Not sure if it'd be a better idea to scroll another editor if the main editor has no matches, and then allow cycling across splitters, what do you think?
> It might be a good idea to disable uppercase/shift selection when switching between editors, but allow it when jumping within the same editor.
Disabled shift for cross-editor jumping, but kept it for `TARGET` mode.
> Cycling with Enter/Shift enter also becomes tricky, not sure how you're planning to handle that.
Cycling is in main editor only, but it could be worth a try to make it …

Implement jumping across splitters

---

src/main/kotlin/org/acejump/action/TagJumper.kt

Using target mode with multiple editors open would select tag in other editor but focus would remain in starting editor.

ensure editor focus also when using select function

---

src/main/kotlin/org/acejump/view/TextHighlighter.kt

Panel background is not visible either way so it can also be removed.
fixes #376

prevent setting INHERITED_COLOR_MARKER as border color

---

README.md
src/main/kotlin/org/acejump/view/TagMarker.kt
src/main/kotlin/org/acejump/view/TextHighlighter.kt

Fixes #362.
I don't know a "proper" solution, but imo it's better than the constant eyesore :P  
Also fixes the text highlighter background starting one pixel too low.
<table>
<tr>
<th>OS</th>
<th>DPI</th>
<th>Retina</th>
<th>Result</th>
</tr>
<tr>
<td rowspan="3">Windows</td>
<td>=&nbsp;100%</td>
<td>✗</td>
<td><strong>OK</strong></td>
</tr>
<tr>
<td>&gt;&nbsp;100%</td>
<td>✗</td>
<td>A hot mess both before and after this change. I'd say anyone who uses Windows on High DPi is already used to it being an utterly terrible experience, so I'm not going to try figure this out.</td>
</tr>
<tr>
<td>&gt;&nbsp;100%</td>
<td>✓</td>
<td><strong>OK</strong></td>
</tr>
<tr>
<td rowspan="2">Linux&nbsp;(KDE)</td>
<td>=&nbsp;100%</td>
<td>✗</td>
<td><strong>OK</strong></td>
</tr>
<tr> …

Workaround tag misalignment on high DPI screens

---

README.md
src/main/kotlin/org/acejump/action/AceAction.kt
src/main/resources/META-INF/plugin.xml

This allows AceJump to have similar behavior to vim-sneak when using `AceForwardAction` and `AceBackwardAction`.

Add bounded toggle mode classes to start jump mode before the caret or after the caret.

---

src/main/resources/META-INF/plugin.xml

This will be needed for IdeaVim plugin to maintain the correct ordering of the handlers.
Well, and this is also good in general.

Add ids to editor action handlers

---

src/main/kotlin/org/acejump/action/AceAction.kt
src/main/kotlin/org/acejump/action/TagJumper.kt

For some reason, I have to use the specific version of IDEA based ide.
I met the error while jumping to the tag, which is quite wired, the error message says "java.lang.NoSuchFieldError: Companion".
I locate the problem is occurred while calling `FileEditorManagerEx.getInstanceEx()` function, so I direct call the inner function instead, then it works.
--- git log below ---
avoid 'java.lang.NoSuchFieldError: Companion' error on lower version IDEA ide such as DevEco Studio, which related to `FileEditorManagerEx.getInstanceEx()` companion
Related issues: [#434](https://github.com/acejump/AceJump/issues/434), [#438](https://github.com/acejump/AceJump/issues/438), [#435](https://github.com/acejump/AceJump/issues/435), etc.

fix(compatibility): avoid 'java.lang.NoSuchFieldError: Companion' error on lower version IDEA ide

---

build.gradle.kts
gradle.properties

Fixes #449
Wanted to run this by you first.
1. Changed the Kotlin plugin version to match the one bundled in IDEA 2023.2 (see comment link for a table)
2. This version of the Kotlin plugin has broken incremental compilation so I disabled that too
3. According to https://kotlinlang.org/docs/gradle-configure-project.html, the toolchain notation can be shortened and it should set `jvmTarget` automatically
I ran into some issues building the plugin in `master` - if I run `buildPlugin` then it crashes on some L&F error during the `test` task... but if I run `test` on its own, and `buildPlugin` without the dependency on `test`, everything succeeds. Not sure if it's just something on my machine, but regardless it's not caused by these changes.

Do not bundle kotlin stdlib

---

src/main/kotlin/org/acejump/search/Solver.kt
src/main/kotlin/org/acejump/search/Tag.kt
src/main/kotlin/org/acejump/search/Tagger.kt
src/main/kotlin/org/acejump/view/TagCanvas.kt

Closes #453
Avoids assigning tags to offsets inside folded regions until you unfold them and refine the query.  
Since the user may fold a region that already has tags, the PR also:
1. Ignores tags inside folded regions when typing
2. Skips rendering tag markers inside folded regions, otherwise it would show tags that cannot be typed
It keeps the search highlights at folded regions so you know they're there, even if it looks a little weird.
I didn't see a good way to consolidate the logic for `in view and not in folded region`, since typing uses `Tag` / `Tagger` and calls `editor.getView()` without any caching, and rendering uses `TagMarker` with an offset cache to determine what is in view.

Do not assign tags inside folded regions

---

src/main/kotlin/org/acejump/input/KeyLayout.kt

Priority reordered for columnar keyboards.
Might be better to just have a custom layout option in the settings instead?

Add ENGRAM key layout

---

src/main/kotlin/org/acejump/boundaries/EditorOffsetCache.kt
src/main/kotlin/org/acejump/boundaries/StandardBoundaries.kt
src/main/kotlin/org/acejump/search/SearchProcessor.kt

When 'Search whole file' is disabled, search results are tested for visibility on the screen. There is already an optimization that only checks results on visible lines, but the number of offset-to-XY conversions still scales linearly with the number of results, which can be very large in files with long lines.
A simple observation is that every line has a first and last offset that is visible on the screen (which may be different for each line due to proportional fonts).
This commit caches the visible offset range for every line involved in one search query, so testing visibility of a search result becomes a check if its offset is inside its line's visible offset range. Finding the visible offset range requires two XY-to-offset conversions per line, so the total number of conversions is …

Optimize screen visibility checks during search

---

src/main/kotlin/org/acejump/view/TagMarker.kt

Paint tag on the right side if the left side is out of bounds
